[tool.poetry]
name = "lms"
version = "0.1.0"
description = ""
authors = ["ipc"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "^0.21.0"
fastapi = "^0.94.0"
pydantic = "^1.10.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
